name: main
on:
  push:
    branches:
    - main

jobs:
  run-tests-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests on ubuntu-latest
      run: python -m unittest tests.py -v
  
  run-tests-windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests on windows-latest
      run: python -m unittest tests.py -v
